import React, { useEffect } from 'react';
import { useAppContext } from '../../AppContext';
import { X, FileText, CloudDownload, Clipboard } from 'lucide-react';

export default function ExportModal() {
  const { setActiveModal, MOCK_PATIENT, findings, annotations } = useAppContext();

  // --- THE FIX: Hide the rest of the app when printing ---
  useEffect(() => {
    // When this modal mounts, add a class to the body that hides the main app during print
    document.body.classList.add('print-modal-active');
    return () => {
      document.body.classList.remove('print-modal-active');
    };
  }, []);

  const handlePrint = () => {
    window.print();
  };

  const copyToClipboard = () => {
    const text = `Patient: ${MOCK_PATIENT.name} (${MOCK_PATIENT.id})\nFindings: ${findings.length}\nAnnotations: ${annotations}`;
    navigator.clipboard.writeText(text);
    alert('Summary copied to clipboard!');
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm p-4 animate-in fade-in duration-200 print:bg-transparent print:backdrop-blur-none print:static print:inset-auto print:p-0">
      <div className="bg-white rounded-2xl shadow-xl border border-border w-full max-w-md flex flex-col overflow-hidden print:shadow-none print:border-none print:w-full print:max-w-none print:p-0">
        
        <div className="flex items-center justify-between px-6 py-4 border-b border-border bg-gray-50 print:hidden">
           <h2 className="text-lg font-bold text-text-primary">Export Report</h2>
           <button onClick={() => setActiveModal(null)} className="p-1.5 hover:bg-gray-200 rounded-md text-muted transition outline-none focus:ring-2 focus:ring-primary/50"><X className="w-5 h-5" /></button>
        </div>
        
        <div className="p-6 flex flex-col space-y-4 print:hidden">
           <p className="text-sm text-gray-600 mb-2 font-medium">Select an export format for the current clinical findings.</p>
           
           <button onClick={handlePrint} className="flex items-center justify-between p-4 border border-border rounded-xl hover:border-primary hover:bg-blue-50 transition-colors group text-left outline-none focus:ring-2 focus:ring-primary/50">
             <div className="flex items-center">
               <div className="p-2.5 bg-blue-100 text-primary rounded-lg mr-4 group-hover:bg-primary group-hover:text-white transition"><FileText className="w-5 h-5" /></div>
               <div>
                 <div className="font-bold text-text-primary">PDF Clinical Report</div>
                 <div className="text-xs text-muted font-medium mt-0.5">Generate a printable document</div>
               </div>
             </div>
           </button>

           <button onClick={() => alert('DICOM export simulated!')} className="flex items-center justify-between p-4 border border-border rounded-xl hover:border-primary hover:bg-blue-50 transition-colors group text-left outline-none focus:ring-2 focus:ring-primary/50">
             <div className="flex items-center">
               <div className="p-2.5 bg-blue-100 text-primary rounded-lg mr-4 group-hover:bg-primary group-hover:text-white transition"><CloudDownload className="w-5 h-5" /></div>
               <div>
                 <div className="font-bold text-text-primary">DICOM JSON Metadata</div>
                 <div className="text-xs text-muted font-medium mt-0.5">Export segmentation coordinates</div>
               </div>
             </div>
           </button>

           <button onClick={copyToClipboard} className="flex items-center justify-between p-4 border border-border rounded-xl hover:border-primary hover:bg-blue-50 transition-colors group text-left outline-none focus:ring-2 focus:ring-primary/50">
             <div className="flex items-center">
               <div className="p-2.5 bg-blue-100 text-primary rounded-lg mr-4 group-hover:bg-primary group-hover:text-white transition"><Clipboard className="w-5 h-5" /></div>
               <div>
                 <div className="font-bold text-text-primary">Copy Summary</div>
                 <div className="text-xs text-muted font-medium mt-0.5">Copy plain text to clipboard</div>
               </div>
             </div>
           </button>
        </div>

        {/* Print Layout (Only visible when printing) */}
        <div className="hidden print:block font-sans text-black">
           <div className="border-b-2 border-black pb-4 mb-6">
              <h1 className="text-3xl font-black uppercase tracking-tight">RPD Diagnostic Report</h1>
              <p className="text-sm font-semibold tracking-wide text-gray-600 mt-1">Generated by 3D U-Net Volumetric AI Scanner</p>
           </div>
           
           <div className="grid grid-cols-2 gap-8 mb-8 text-sm">
              <div>
                <p><span className="font-bold w-32 inline-block">Patient Name:</span> {MOCK_PATIENT.name}</p>
                <p><span className="font-bold w-32 inline-block">Patient ID:</span> {MOCK_PATIENT.id}</p>
                <p><span className="font-bold w-32 inline-block">Demographics:</span> {MOCK_PATIENT.gender}, {MOCK_PATIENT.age}</p>
              </div>
              <div>
                <p><span className="font-bold w-32 inline-block">Scan Date:</span> {MOCK_PATIENT.scanDate}</p>
                <p><span className="font-bold w-32 inline-block">Physician:</span> {MOCK_PATIENT.physician}</p>
                <p><span className="font-bold w-32 inline-block">Report Date:</span> {new Date().toLocaleDateString()}</p>
              </div>
           </div>

           <h2 className="text-lg font-bold uppercase tracking-wider border-b border-gray-300 pb-2 mb-4">Detected Findings ({findings.length})</h2>
           {findings.length === 0 ? (
             <p className="text-gray-600 italic mb-8">No suspicious volumetric findings detected exceeding the confidence threshold.</p>
           ) : (
             <table className="w-full text-left text-sm mb-8 border border-gray-300">
               <thead>
                 <tr className="bg-gray-100 uppercase text-xs">
                   <th className="p-2 border-b border-gray-300">#</th>
                   <th className="p-2 border-b border-gray-300">Slice Depth</th>
                   <th className="p-2 border-b border-gray-300">Location</th>
                   <th className="p-2 border-b border-gray-300">AI Confidence</th>
                 </tr>
               </thead>
               <tbody>
                  {findings.map(f => (
                    <tr key={f.id} className="border-b border-gray-200">
                      <td className="p-2 font-bold">{f.id}</td>
                      <td className="p-2 font-mono">{f.sliceRange}</td>
                      <td className="p-2">{f.location}</td>
                      <td className="p-2 font-bold text-red-600">{f.confidence}%</td>
                    </tr>
                  ))}
               </tbody>
             </table>
           )}

           <h2 className="text-lg font-bold uppercase tracking-wider border-b border-gray-300 pb-2 mb-4">Clinical Annotations</h2>
           <p className="whitespace-pre-wrap text-sm leading-relaxed text-gray-800">{annotations || 'No annotations provided.'}</p>
           
           <div className="mt-16 pt-8 border-t border-gray-300 text-sm">
              <div className="w-64 border-b border-black mb-2"></div>
              <p className="font-bold">{MOCK_PATIENT.physician}</p>
              <p className="text-gray-600 text-xs mt-1">Reviewing Medical Officer</p>
           </div>
        </div>

      </div>
    </div>
  );
}